# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Location.create(location: 'Honolulu', county: 'Honolulu')
Location.create(location: 'East Honolulu', county: 'Honolulu')
Location.create(location: 'Pearl City', county: 'Honolulu')
Location.create(location: 'Hilo', county: 'Hawaii')
Location.create(location: 'Kailua', county: 'Honolulu')
Location.create(location: 'Waipahu', county: 'Honolulu')
Location.create(location: 'Kaneohe', county: 'Honolulu')
Location.create(location: 'Mililani Town', county: 'Honolulu')
Location.create(location: 'Kahului', county: 'Maui')
Location.create(location: 'Ewa Gentry', county: 'Honolulu')
Location.create(location: 'Mililani Mauka', county: 'Honolulu')
Location.create(location: 'Kihei', county: 'Maui')
Location.create(location: 'Makakilo', county: 'Honolulu')
Location.create(location: 'Wahiawa', county: 'Honolullu')
Location.create(location: 'Schofiled Barracks', county: 'Honolulu')
Location.create(location: 'Wailuku', county: 'Maui')
Location.create(location: 'Kapolei', county: 'Honolulu')
Location.create(location: 'Ewa Beach', county: 'Honolulu')
Location.create(location: 'Royal Kunia', county: 'Honolulu')
Location.create(location: 'Halawa', county: 'Honolulu')
Location.create(location: 'Waimalu', county: 'Honolulu')
Location.create(location: 'Waianae', county: 'Honolulu')
Location.create(location: 'Nanakuli', county: 'Honolulu')
Location.create(location: 'Kailua', county: 'Honolulu')
Location.create(location: 'Lahaina', county: 'Maui')
Location.create(location: 'Waipio', county: 'Honolulu')
Location.create(location: 'Hawaiian Paradise Park', county: 'Hawaii')
Location.create(location: 'Kapaa', county: 'Kauai')
Location.create(location: 'Kalaoa', county: 'Hawaii')
Location.create(location: 'Kaneohe Station', county: 'Honolulu')
Location.create(location: 'Maili', county: 'Honolulu')
Location.create(location: 'Aiea', county: 'Honolulu')
Location.create(location: 'Waimea', county: 'Hawaii')
Location.create(location: 'Waihee-Waiehu', county: 'Maui')
Location.create(location: 'Ahuimanu', county: 'Honolulu')
Location.create(location: 'Holualoa', county: 'Honolulu')
Location.create(location: 'Ocean Pointe', county: 'Honolulu')
Location.create(location: 'Makaha', county: 'Honolulu')
Location.create(location: 'Haiku-Pauwela', county: 'Maui')
Location.create(location: 'Pukalani', county: 'Maui')
Location.create(location: 'Waikele', county: 'Honolulu')
Location.create(location: 'Napili-Honokowai', county: 'Maui')
Location.create(location: 'Makawao', county: 'Maui')
Location.create(location: 'Hickam Housing', county: 'Honolulu')
Location.create(location: 'Lihue', county: 'Kauai')
Location.create(location: 'Kula', county: 'Maui')
Location.create(location: 'Waikoloa Village', county: 'Hawaii')
Location.create(location: 'Laie', county: 'Honolulu')
Location.create(location: 'Ewa Villages', county: 'Honolulu')
Location.create(location: 'Wailea', county: 'Maui')
Location.create(location: 'West Loch Estate', county: 'Honolulu')
Location.create(location: 'Waimanalo', county: 'Honolulu')
Location.create(location: 'Waipio Acres', county: 'Honolulu')
Location.create(location: 'Wailua Homesteads', county: 'Kauai')
Location.create(location: 'Heeia', county: 'Honolulu')
Location.create(location: 'Kahaluu', county: 'Honolulu')
Location.create(location: 'Klaheo', county: 'Kauai')
Location.create(location: 'Pupukea', county: 'Honolulu')
Location.create(location: 'Whitmore Village', county: 'Honolulu')
Location.create(location: 'Waimanalo Beach', county: 'Honolulu')
Location.create(location: 'Hawaiian Ocean View', county: 'Hawaii')
Location.create(location: 'Hawaiian Beaches', county: 'Hawaii')
Location.create(location: 'Hauula', county: 'Honolulu')
Location.create(location: 'Haleiwa', county: 'Honolulu')
Location.create(location: 'Mountain View', county: 'Hawaii')
Location.create(location: 'Waialua', county: 'Honolulu')
Location.create(location: 'Hanamaulu', county: 'Kauai')
Location.create(location: 'Kahaluu-Keauhou', county: 'Hawaii')
Location.create(location: 'Kekaha', county: 'Kauai')
Location.create(location: 'Captain Cook', county: 'Hawaii')
Location.create(location: 'Kaunakakai', county: 'Maui')
Location.create(location: 'Iroquois Point', county: 'Honolulu')
Location.create(location: 'Lanai City', county: 'Maui')
Location.create(location: 'Ainaloa', county: 'Hawaii')
Location.create(location: 'Waikapu', county: 'Maui')
Location.create(location: 'Puhi', county: 'Kauai')
Location.create(location: 'Orchidlands Estate', county: 'Hawaii')
Location.create(location: 'Kilauea', county: 'Kauai')
Location.create(location: 'Hawaiian Acres', county: 'Hawaii')
Location.create(location: 'Paia', county: 'Maui')
Location.create(location: 'Hanapepe', county: 'Kauai')
Location.create(location: 'Kahuku', county: 'Honolulu')
Location.create(location: 'Volcano', county: 'Hawaii')
Location.create(location: 'Honaunau-Napoopoo', county: 'Hawaii')
Location.create(location: 'Honalo', county: 'Hawaii')
Location.create(location: 'Eleele', county: 'Kauai')
Location.create(location: 'Lawai', county: 'Kauai')
Location.create(location: 'Honokea', county: 'Hawaii')
Location.create(location: 'Wailua', county: 'Kauai')
Location.create(location: 'Keaau', county: 'Hawaii')
Location.create(location: 'Anaholea', county: 'Kauai')
Location.create(location: 'Princeville', county: 'Kauai')
Location.create(location: 'Koloa', county: 'Kauai')
Location.create(location: 'Maunawili', county: 'Honolulu')
Location.create(location: 'Kualapuu', county: 'Maui')
Location.create(location: 'Kealakekua', county: 'Hawaii')
Location.create(location: 'Waimea', county: 'Kauai')
Location.create(location: 'Mokuleia', county: 'Honolulu')
Location.create(location: 'Ko Olina', county: 'Honolulu')
Location.create(location: 'Pepeekeo', county: 'Hawaii')
Location.create(location: 'Kapaau', county: 'Hawaii')
Location.create(location: 'Wheeler AFB', county: 'Honolulu')
Location.create(location: 'Keokea', county: 'Maui')
Location.create(location: 'Leilani Estates', county: 'Hawaii')
Location.create(location: 'Fern Acres', county: 'Hawaii')
Location.create(location: 'Nanawale Estates', county: 'Hawaii')
Location.create(location: 'Kaawa', county: 'Honolulu')
Location.create(location: 'Pahala', county: 'Hawaii')
Location.create(location: 'Makaha Valley', county: 'Honolulu')
Location.create(location: 'Papaikou', county: 'Hawaii')
Location.create(location: 'Omao', county: 'Kauai')
Location.create(location: 'Kurtistown', county: 'Hawaii')
Location.create(location: 'Hana', county: 'Maui')
Location.create(location: 'Wainaku', county: 'Hawaii')
Location.create(location: 'Punaluu', county: 'Honolulu')
Location.create(location: 'Olinda', county: 'Maui')
Location.create(location: 'Hawi', county: 'Hawaii')
Location.create(location: 'Kaanapali', county: 'Maui')
Location.create(location: 'Poipu', county: 'Kauai')
Location.create(location: 'Haliimaile', county: 'Maui')
Location.create(location: 'Discovery Harbour', county: 'Hawaii')
Location.create(location: 'Pahoa', county: 'Hawaii')
Location.create(location: 'Eden Roc', county: 'Hawaii')
Location.create(location: 'Fern Forest', county: 'Hawaii')
Location.create(location: 'Mahinahina', county: 'Maui')
Location.create(location: 'Naalehu', county: 'Hawaii')
Location.create(location: 'Waikane', county: 'Honolulu')
Location.create(location: 'Puako', county: 'Hawaii')
Location.create(location: 'Kaumakeni', county: 'Kauai')
Location.create(location: 'Paauilo', county: 'Hawaii')
Location.create(location: 'Launaiupoko', county: 'Maui')
Location.create(location: 'Laupahoehoe', county: 'Hawaii')
Location.create(location: 'Monomu', county: 'Hawaii')
Location.create(location: 'Halaula', county: 'Hawaii')
Location.create(location: 'Hanalei', county: 'Kauai')
Location.create(location: 'Haena', county: 'Kauai')
Location.create(location: 'Kalihiwai', county: 'Kauai')
Location.create(location: 'Paukea', county: 'Hawaii')
Location.create(location: 'Ualapue', county: 'Maui')
Location.create(location: 'Maunaloa', county: 'Maui')
Location.create(location: 'Kapalua', county: 'Maui')
Location.create(location: 'Maalaea', county: 'Maui')
Location.create(location: 'Kukuihaele', county: 'Hawaii')
Location.create(location: 'Kawela Bay', county: 'Honolulu')
Location.create(location: 'Wainiha', county: 'Kauai')
Location.create(location: 'Pakala Villiage', county: 'Kauai')
Location.create(location: 'Waiohinu', county: 'Hawaii')
Location.create(location: 'Makena', county: 'Maui')
Location.create(location: 'Olowalu', county: 'Maui')
Location.create(location: 'Kalaeloa', county: 'Honolulu')
Location.create(location: 'Manele', county: 'Maui')
